SELECT
YEAR(SALES_DATE) AS YEAR,
MONTH(SALES_DATE) AS MONTH,
COUNT(DISTINCT USER_ID) AS PURCHASED_USERS,
ROUND(COUNT(DISTINCT UI.USER_ID)/(
    SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED)=2021), 1) AS PURCHASE_RATIO
FROM ONLINE_SALE OS JOIN USER_INFO UI USING (USER_ID)
WHERE YEAR(JOINED)=2021
GROUP BY 1, 2 ORDER BY 1, 2;