#WITH TBL AS (
 #   SELECT H.FLAVOR, SUM(H.TOTAL_ORDER)+SUM(J.TOTAL_ORDER) AS ALL_PLUS
  #  FROM FIRST_HALF H JOIN JULY J USING (SHIPMENT_ID)
   # GROUP BY FLAVOR ORDER BY ALL_PLUS DESC)

SELECT F.FLAVOR FROM FIRST_HALF F
JOIN ( SELECT SHIPMENT_ID, FLAVOR, SUM(TOTAL_ORDER) AS JULY_PLUS FROM JULY
        GROUP BY FLAVOR ORDER BY JULY_PLUS DESC) J
ON F.FLAVOR=J.FLAVOR
GROUP BY F.FLAVOR
ORDER BY (F.TOTAL_ORDER+J.JULY_PLUS) DESC LIMIT 3;