SELECT HOUR, COUNT(ANIMAL_ID) AS COUNT
FROM (
    SELECT (ROW_NUMBER() OVER () -1) AS HOUR
    FROM INFORMATION_SCHEMA.TABLES LIMIT 24 ) TBL
LEFT JOIN ANIMAL_OUTS ON HOUR = HOUR(DATETIME)
GROUP BY 1 ORDER BY 1;