WITH TBL AS (SELECT SUM(SCORE) AS SCORE, E.EMP_NO, EMP_NAME, POSITION, EMAIL,
    RANK() OVER(ORDER BY SUM(SCORE) DESC) AS RNK
FROM HR_EMPLOYEES E
JOIN HR_GRADE G USING (EMP_NO)
GROUP BY 2 )

SELECT SCORE, EMP_NO, EMP_NAME, POSITION, EMAIL
FROM TBL WHERE RNK=1;